name: Publish Python distributions to PyPI and TestPyPI

on:
  workflow_dispatch:

jobs:
    python-build-n-publish:
        name: Build and publish Python distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: Initialize Python 3.9
              uses: actions/setup-python@v1
              with:
                python-version: 3.9

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
          
            - name: Build binary wheel and a source tarball
              run: python setup.py sdist

            - name: Publish distribution to PyPI
              uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
              with:
                password: ${{ secrets.PYPI_API }}
                repository_url: https://upload.pypi.org/legacy/
